# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dap_flash_pb2 as dap__flash__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dap_flash_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DapFlashServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProbes = channel.unary_unary(
                '/dap_flash.DapFlashService/ListProbes',
                request_serializer=dap__flash__pb2.ListProbesRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.ProbeList.FromString,
                _registered_method=True)
        self.ConnectProbe = channel.unary_unary(
                '/dap_flash.DapFlashService/ConnectProbe',
                request_serializer=dap__flash__pb2.ConnectRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.DisconnectProbe = channel.unary_unary(
                '/dap_flash.DapFlashService/DisconnectProbe',
                request_serializer=dap__flash__pb2.DisconnectProbeRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.DisconnectProbeResponse.FromString,
                _registered_method=True)
        self.GetProbeDetails = channel.unary_unary(
                '/dap_flash.DapFlashService/GetProbeDetails',
                request_serializer=dap__flash__pb2.GetProbeDetailsRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.ProbeDetails.FromString,
                _registered_method=True)
        self.FlashFirmware = channel.unary_stream(
                '/dap_flash.DapFlashService/FlashFirmware',
                request_serializer=dap__flash__pb2.FlashRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.ProgressUpdate.FromString,
                _registered_method=True)
        self.EraseChip = channel.unary_stream(
                '/dap_flash.DapFlashService/EraseChip',
                request_serializer=dap__flash__pb2.EraseRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.ProgressUpdate.FromString,
                _registered_method=True)
        self.ResetTarget = channel.unary_unary(
                '/dap_flash.DapFlashService/ResetTarget',
                request_serializer=dap__flash__pb2.ResetRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.OperationResult.FromString,
                _registered_method=True)
        self.ReadChipId = channel.unary_unary(
                '/dap_flash.DapFlashService/ReadChipId',
                request_serializer=dap__flash__pb2.ReadChipIdRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.ChipIdResult.FromString,
                _registered_method=True)
        self.ListPacks = channel.unary_unary(
                '/dap_flash.DapFlashService/ListPacks',
                request_serializer=dap__flash__pb2.ListPacksRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.PackList.FromString,
                _registered_method=True)
        self.SearchPacks = channel.unary_unary(
                '/dap_flash.DapFlashService/SearchPacks',
                request_serializer=dap__flash__pb2.SearchRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.PackSearchResult.FromString,
                _registered_method=True)
        self.DownloadPack = channel.unary_stream(
                '/dap_flash.DapFlashService/DownloadPack',
                request_serializer=dap__flash__pb2.DownloadRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.ProgressUpdate.FromString,
                _registered_method=True)
        self.InstallPack = channel.unary_unary(
                '/dap_flash.DapFlashService/InstallPack',
                request_serializer=dap__flash__pb2.InstallPackRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.OperationResult.FromString,
                _registered_method=True)
        self.ListInstalledPacks = channel.unary_unary(
                '/dap_flash.DapFlashService/ListInstalledPacks',
                request_serializer=dap__flash__pb2.ListInstalledPacksRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.InstalledPackList.FromString,
                _registered_method=True)
        self.PreviewFirmware = channel.unary_unary(
                '/dap_flash.DapFlashService/PreviewFirmware',
                request_serializer=dap__flash__pb2.PreviewRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.PreviewResponse.FromString,
                _registered_method=True)
        self.GetFileInfo = channel.unary_unary(
                '/dap_flash.DapFlashService/GetFileInfo',
                request_serializer=dap__flash__pb2.PreviewRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.FileInfo.FromString,
                _registered_method=True)
        self.GetFlashHistory = channel.unary_unary(
                '/dap_flash.DapFlashService/GetFlashHistory',
                request_serializer=dap__flash__pb2.GetFlashHistoryRequest.SerializeToString,
                response_deserializer=dap__flash__pb2.FlashHistoryList.FromString,
                _registered_method=True)


class DapFlashServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListProbes(self, request, context):
        """Device management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectProbe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectProbe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProbeDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlashFirmware(self, request, context):
        """Flash operations (streaming progress)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EraseChip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadChipId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPacks(self, request, context):
        """Pack management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadPack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallPack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstalledPacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewFirmware(self, request, context):
        """File preview
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlashHistory(self, request, context):
        """History
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DapFlashServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProbes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProbes,
                    request_deserializer=dap__flash__pb2.ListProbesRequest.FromString,
                    response_serializer=dap__flash__pb2.ProbeList.SerializeToString,
            ),
            'ConnectProbe': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectProbe,
                    request_deserializer=dap__flash__pb2.ConnectRequest.FromString,
                    response_serializer=dap__flash__pb2.ConnectResponse.SerializeToString,
            ),
            'DisconnectProbe': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectProbe,
                    request_deserializer=dap__flash__pb2.DisconnectProbeRequest.FromString,
                    response_serializer=dap__flash__pb2.DisconnectProbeResponse.SerializeToString,
            ),
            'GetProbeDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProbeDetails,
                    request_deserializer=dap__flash__pb2.GetProbeDetailsRequest.FromString,
                    response_serializer=dap__flash__pb2.ProbeDetails.SerializeToString,
            ),
            'FlashFirmware': grpc.unary_stream_rpc_method_handler(
                    servicer.FlashFirmware,
                    request_deserializer=dap__flash__pb2.FlashRequest.FromString,
                    response_serializer=dap__flash__pb2.ProgressUpdate.SerializeToString,
            ),
            'EraseChip': grpc.unary_stream_rpc_method_handler(
                    servicer.EraseChip,
                    request_deserializer=dap__flash__pb2.EraseRequest.FromString,
                    response_serializer=dap__flash__pb2.ProgressUpdate.SerializeToString,
            ),
            'ResetTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetTarget,
                    request_deserializer=dap__flash__pb2.ResetRequest.FromString,
                    response_serializer=dap__flash__pb2.OperationResult.SerializeToString,
            ),
            'ReadChipId': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadChipId,
                    request_deserializer=dap__flash__pb2.ReadChipIdRequest.FromString,
                    response_serializer=dap__flash__pb2.ChipIdResult.SerializeToString,
            ),
            'ListPacks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPacks,
                    request_deserializer=dap__flash__pb2.ListPacksRequest.FromString,
                    response_serializer=dap__flash__pb2.PackList.SerializeToString,
            ),
            'SearchPacks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPacks,
                    request_deserializer=dap__flash__pb2.SearchRequest.FromString,
                    response_serializer=dap__flash__pb2.PackSearchResult.SerializeToString,
            ),
            'DownloadPack': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadPack,
                    request_deserializer=dap__flash__pb2.DownloadRequest.FromString,
                    response_serializer=dap__flash__pb2.ProgressUpdate.SerializeToString,
            ),
            'InstallPack': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallPack,
                    request_deserializer=dap__flash__pb2.InstallPackRequest.FromString,
                    response_serializer=dap__flash__pb2.OperationResult.SerializeToString,
            ),
            'ListInstalledPacks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstalledPacks,
                    request_deserializer=dap__flash__pb2.ListInstalledPacksRequest.FromString,
                    response_serializer=dap__flash__pb2.InstalledPackList.SerializeToString,
            ),
            'PreviewFirmware': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewFirmware,
                    request_deserializer=dap__flash__pb2.PreviewRequest.FromString,
                    response_serializer=dap__flash__pb2.PreviewResponse.SerializeToString,
            ),
            'GetFileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileInfo,
                    request_deserializer=dap__flash__pb2.PreviewRequest.FromString,
                    response_serializer=dap__flash__pb2.FileInfo.SerializeToString,
            ),
            'GetFlashHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlashHistory,
                    request_deserializer=dap__flash__pb2.GetFlashHistoryRequest.FromString,
                    response_serializer=dap__flash__pb2.FlashHistoryList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dap_flash.DapFlashService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dap_flash.DapFlashService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DapFlashService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProbes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/ListProbes',
            dap__flash__pb2.ListProbesRequest.SerializeToString,
            dap__flash__pb2.ProbeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectProbe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/ConnectProbe',
            dap__flash__pb2.ConnectRequest.SerializeToString,
            dap__flash__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectProbe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/DisconnectProbe',
            dap__flash__pb2.DisconnectProbeRequest.SerializeToString,
            dap__flash__pb2.DisconnectProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProbeDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/GetProbeDetails',
            dap__flash__pb2.GetProbeDetailsRequest.SerializeToString,
            dap__flash__pb2.ProbeDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlashFirmware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dap_flash.DapFlashService/FlashFirmware',
            dap__flash__pb2.FlashRequest.SerializeToString,
            dap__flash__pb2.ProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EraseChip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dap_flash.DapFlashService/EraseChip',
            dap__flash__pb2.EraseRequest.SerializeToString,
            dap__flash__pb2.ProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/ResetTarget',
            dap__flash__pb2.ResetRequest.SerializeToString,
            dap__flash__pb2.OperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadChipId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/ReadChipId',
            dap__flash__pb2.ReadChipIdRequest.SerializeToString,
            dap__flash__pb2.ChipIdResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/ListPacks',
            dap__flash__pb2.ListPacksRequest.SerializeToString,
            dap__flash__pb2.PackList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/SearchPacks',
            dap__flash__pb2.SearchRequest.SerializeToString,
            dap__flash__pb2.PackSearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadPack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dap_flash.DapFlashService/DownloadPack',
            dap__flash__pb2.DownloadRequest.SerializeToString,
            dap__flash__pb2.ProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallPack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/InstallPack',
            dap__flash__pb2.InstallPackRequest.SerializeToString,
            dap__flash__pb2.OperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstalledPacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/ListInstalledPacks',
            dap__flash__pb2.ListInstalledPacksRequest.SerializeToString,
            dap__flash__pb2.InstalledPackList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewFirmware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/PreviewFirmware',
            dap__flash__pb2.PreviewRequest.SerializeToString,
            dap__flash__pb2.PreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/GetFileInfo',
            dap__flash__pb2.PreviewRequest.SerializeToString,
            dap__flash__pb2.FileInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlashHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dap_flash.DapFlashService/GetFlashHistory',
            dap__flash__pb2.GetFlashHistoryRequest.SerializeToString,
            dap__flash__pb2.FlashHistoryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
