analyzer:
  exclude:
    - "lib/proto/**"
    - "lib/services/grpc_client.dart"
    - "lib/services/device_service.dart"
    - "lib/services/flash_service.dart"
  errors:
    deprecated_member_use: info
    uri_does_not_exist: ignore
    uri_has_not_been_generated: ignore
