name: dap_flash_tool
description: DAP-Link firmware flashing tool
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  grpc: ^4.0.0
  protobuf: ^4.0.0
  fixnum: ^1.1.0
  path_provider: ^2.1.0
  file_picker: ^6.1.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.2.0
  flutter_animate: ^4.5.2
  google_fonts: ^8.2.1
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  protoc_plugin: ^22.0.0

flutter:
  uses-material-design: true
