// Generated stubs for dap_flash.proto
// In production, this file is generated by protoc --dart_out=grpc:lib/proto
import 'package:protobuf/protobuf.dart';

// ── Probe ──
class Probe extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('Probe')
    ..aOS(1, 'id')
    ..aOS(2, 'name')
    ..aOS(3, 'vendor')
    ..aOS(4, 'serialNumber', protoName: 'serial_number')
    ..hasRequiredFields = false;

  Probe() : super();
  Probe.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  Probe.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  String get id => $_getSZ(0);
  set id(String v) { $_setString(0, v); }
  bool hasId() => $_has(0);
  void clearId() => clearField(1);

  String get name => $_getSZ(1);
  set name(String v) { $_setString(1, v); }
  bool hasName() => $_has(1);
  void clearName() => clearField(2);

  String get vendor => $_getSZ(2);
  set vendor(String v) { $_setString(2, v); }
  bool hasVendor() => $_has(2);
  void clearVendor() => clearField(3);

  String get serialNumber => $_getSZ(3);
  set serialNumber(String v) { $_setString(3, v); }
  bool hasSerialNumber() => $_has(3);
  void clearSerialNumber() => clearField(4);

  static Probe create() => Probe();
  static PbList<Probe> createRepeated() => PbList<Probe>();
  static Probe getDefault() => _defaultInstance ??= create()..freeze();
  static Probe? _defaultInstance;
}

// ── ProbeList ──
class ProbeList extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('ProbeList')
    ..pc<Probe>(1, 'probes', PbFieldType.PM, Probe.create)
    ..hasRequiredFields = false;

  ProbeList() : super();
  ProbeList.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  ProbeList.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  List<Probe> get probes => $_getList(0);

  static ProbeList create() => ProbeList();
  static PbList<ProbeList> createRepeated() => PbList<ProbeList>();
  static ProbeList getDefault() => _defaultInstance ??= create()..freeze();
  static ProbeList? _defaultInstance;
}

// ── ConnectRequest ──
class ConnectRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('ConnectRequest')
    ..aOS(1, 'probeId', protoName: 'probe_id')
    ..aOS(2, 'target')
    ..a<int>(3, 'frequency', PbFieldType.O3)
    ..aOS(4, 'protocol')
    ..hasRequiredFields = false;

  ConnectRequest() : super();
  ConnectRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  ConnectRequest.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  String get probeId => $_getSZ(0);
  set probeId(String v) { $_setString(0, v); }
  bool hasProbeId() => $_has(0);
  void clearProbeId() => clearField(1);

  String get target => $_getSZ(1);
  set target(String v) { $_setString(1, v); }
  bool hasTarget() => $_has(1);
  void clearTarget() => clearField(2);

  int get frequency => $_getIZ(2);
  set frequency(int v) { $_setSignedInt32(2, v); }
  bool hasFrequency() => $_has(2);
  void clearFrequency() => clearField(3);

  String get protocol => $_getSZ(3);
  set protocol(String v) { $_setString(3, v); }
  bool hasProtocol() => $_has(3);
  void clearProtocol() => clearField(4);

  static ConnectRequest create() => ConnectRequest();
  static PbList<ConnectRequest> createRepeated() => PbList<ConnectRequest>();
  static ConnectRequest getDefault() => _defaultInstance ??= create()..freeze();
  static ConnectRequest? _defaultInstance;
}

// ── ConnectResponse ──
class ConnectResponse extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('ConnectResponse')
    ..aOB(1, 'success')
    ..aOS(2, 'errorMessage', protoName: 'error_message')
    ..aOS(3, 'targetName', protoName: 'target_name')
    ..hasRequiredFields = false;

  ConnectResponse() : super();
  ConnectResponse.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  ConnectResponse.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  bool get success => $_getBF(0);
  set success(bool v) { $_setBool(0, v); }
  bool hasSuccess() => $_has(0);
  void clearSuccess() => clearField(1);

  String get errorMessage => $_getSZ(1);
  set errorMessage(String v) { $_setString(1, v); }
  bool hasErrorMessage() => $_has(1);
  void clearErrorMessage() => clearField(2);

  String get targetName => $_getSZ(2);
  set targetName(String v) { $_setString(2, v); }
  bool hasTargetName() => $_has(2);
  void clearTargetName() => clearField(3);

  static ConnectResponse create() => ConnectResponse();
  static PbList<ConnectResponse> createRepeated() => PbList<ConnectResponse>();
  static ConnectResponse getDefault() => _defaultInstance ??= create()..freeze();
  static ConnectResponse? _defaultInstance;
}

// ── ProgressUpdate ──
class ProgressUpdate extends GeneratedMessage {
  static const int CONNECTING = 0;
  static const int ERASING = 1;
  static const int PROGRAMMING = 2;
  static const int VERIFYING = 3;
  static const int RESETTING = 4;

  static final BuilderInfo _i = BuilderInfo('ProgressUpdate')
    ..a<int>(1, 'phase', PbFieldType.O3)
    ..a<double>(2, 'progress', PbFieldType.OF)
    ..aInt64(3, 'bytesWritten', protoName: 'bytes_written')
    ..aInt64(4, 'totalBytes', protoName: 'total_bytes')
    ..aOS(5, 'message')
    ..hasRequiredFields = false;

  ProgressUpdate() : super();
  ProgressUpdate.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  ProgressUpdate.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  int get phase => $_getIZ(0);
  set phase(int v) { $_setSignedInt32(0, v); }
  bool hasPhase() => $_has(0);
  void clearPhase() => clearField(1);

  double get progress => $_getN(1);
  set progress(double v) { $_setFloat(1, v); }
  bool hasProgress() => $_has(1);
  void clearProgress() => clearField(2);

  Int64 get bytesWritten => $_getI64(2);
  set bytesWritten(Int64 v) { $_setInt64(2, v); }
  bool hasBytesWritten() => $_has(2);
  void clearBytesWritten() => clearField(3);

  Int64 get totalBytes => $_getI64(3);
  set totalBytes(Int64 v) { $_setInt64(3, v); }
  bool hasTotalBytes() => $_has(3);
  void clearTotalBytes() => clearField(4);

  String get message => $_getSZ(4);
  set message(String v) { $_setString(4, v); }
  bool hasMessage() => $_has(4);
  void clearMessage() => clearField(5);

  static ProgressUpdate create() => ProgressUpdate();
  static PbList<ProgressUpdate> createRepeated() => PbList<ProgressUpdate>();
  static ProgressUpdate getDefault() => _defaultInstance ??= create()..freeze();
  static ProgressUpdate? _defaultInstance;
}

// ── OperationResult ──
class OperationResult extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('OperationResult')
    ..aOB(1, 'success')
    ..aOS(2, 'message')
    ..hasRequiredFields = false;

  OperationResult() : super();
  OperationResult.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  OperationResult.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  bool get success => $_getBF(0);
  set success(bool v) { $_setBool(0, v); }
  bool hasSuccess() => $_has(0);
  void clearSuccess() => clearField(1);

  String get message => $_getSZ(1);
  set message(String v) { $_setString(1, v); }
  bool hasMessage() => $_has(1);
  void clearMessage() => clearField(2);

  static OperationResult create() => OperationResult();
  static PbList<OperationResult> createRepeated() => PbList<OperationResult>();
  static OperationResult getDefault() => _defaultInstance ??= create()..freeze();
  static OperationResult? _defaultInstance;
}

// ── ChipIdResult ──
class ChipIdResult extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('ChipIdResult')
    ..a<int>(1, 'chipId', PbFieldType.OU3, protoName: 'chip_id')
    ..aOS(2, 'description')
    ..hasRequiredFields = false;

  ChipIdResult() : super();
  ChipIdResult.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  ChipIdResult.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  int get chipId => $_getIZ(0);
  set chipId(int v) { $_setUnsignedInt32(0, v); }
  bool hasChipId() => $_has(0);
  void clearChipId() => clearField(1);

  String get description => $_getSZ(1);
  set description(String v) { $_setString(1, v); }
  bool hasDescription() => $_has(1);
  void clearDescription() => clearField(2);

  static ChipIdResult create() => ChipIdResult();
  static PbList<ChipIdResult> createRepeated() => PbList<ChipIdResult>();
  static ChipIdResult getDefault() => _defaultInstance ??= create()..freeze();
  static ChipIdResult? _defaultInstance;
}

// ── EraseRequest ──
class EraseRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('EraseRequest')
    ..aOS(1, 'mode')
    ..hasRequiredFields = false;

  EraseRequest() : super();
  EraseRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  EraseRequest.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  String get mode => $_getSZ(0);
  set mode(String v) { $_setString(0, v); }
  bool hasMode() => $_has(0);
  void clearMode() => clearField(1);

  static EraseRequest create() => EraseRequest();
  static PbList<EraseRequest> createRepeated() => PbList<EraseRequest>();
  static EraseRequest getDefault() => _defaultInstance ??= create()..freeze();
  static EraseRequest? _defaultInstance;
}

// ── FlashRequest ──
class FlashRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('FlashRequest')
    ..aOS(1, 'firmwarePath', protoName: 'firmware_path')
    ..aInt64(2, 'startAddress', protoName: 'start_address')
    ..aOS(3, 'driver')
    ..hasRequiredFields = false;

  FlashRequest() : super();
  FlashRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  FlashRequest.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  String get firmwarePath => $_getSZ(0);
  set firmwarePath(String v) { $_setString(0, v); }
  bool hasFirmwarePath() => $_has(0);
  void clearFirmwarePath() => clearField(1);

  Int64 get startAddress => $_getI64(1);
  set startAddress(Int64 v) { $_setInt64(1, v); }
  bool hasStartAddress() => $_has(1);
  void clearStartAddress() => clearField(2);

  String get driver => $_getSZ(2);
  set driver(String v) { $_setString(2, v); }
  bool hasDriver() => $_has(2);
  void clearDriver() => clearField(3);

  static FlashRequest create() => FlashRequest();
  static PbList<FlashRequest> createRepeated() => PbList<FlashRequest>();
  static FlashRequest getDefault() => _defaultInstance ??= create()..freeze();
  static FlashRequest? _defaultInstance;
}

// ── PackInfo ──
class PackInfo extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('PackInfo')
    ..aOS(1, 'name')
    ..aOS(2, 'vendor')
    ..aOS(3, 'version')
    ..aOS(4, 'path')
    ..pPS(5, 'supportedChips', protoName: 'supported_chips')
    ..hasRequiredFields = false;

  PackInfo() : super();
  PackInfo.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  PackInfo.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  String get name => $_getSZ(0);
  set name(String v) { $_setString(0, v); }
  bool hasName() => $_has(0);
  void clearName() => clearField(1);

  String get vendor => $_getSZ(1);
  set vendor(String v) { $_setString(1, v); }
  bool hasVendor() => $_has(1);
  void clearVendor() => clearField(2);

  String get version => $_getSZ(2);
  set version(String v) { $_setString(2, v); }
  bool hasVersion() => $_has(2);
  void clearVersion() => clearField(3);

  String get path => $_getSZ(3);
  set path(String v) { $_setString(3, v); }
  bool hasPath() => $_has(3);
  void clearPath() => clearField(4);

  List<String> get supportedChips => $_getList(4);

  static PackInfo create() => PackInfo();
  static PbList<PackInfo> createRepeated() => PbList<PackInfo>();
  static PackInfo getDefault() => _defaultInstance ??= create()..freeze();
  static PackInfo? _defaultInstance;
}

// ── PackList ──
class PackList extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('PackList')
    ..pc<PackInfo>(1, 'packs', PbFieldType.PM, PackInfo.create)
    ..hasRequiredFields = false;

  PackList() : super();
  PackList.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  PackList.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  List<PackInfo> get packs => $_getList(0);

  static PackList create() => PackList();
  static PbList<PackList> createRepeated() => PbList<PackList>();
  static PackList getDefault() => _defaultInstance ??= create()..freeze();
  static PackList? _defaultInstance;
}

// ── SearchRequest ──
class SearchRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('SearchRequest')
    ..aOS(1, 'query')
    ..hasRequiredFields = false;

  SearchRequest() : super();
  SearchRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  SearchRequest.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  String get query => $_getSZ(0);
  set query(String v) { $_setString(0, v); }
  bool hasQuery() => $_has(0);
  void clearQuery() => clearField(1);

  static SearchRequest create() => SearchRequest();
  static PbList<SearchRequest> createRepeated() => PbList<SearchRequest>();
  static SearchRequest getDefault() => _defaultInstance ??= create()..freeze();
  static SearchRequest? _defaultInstance;
}

// ── PackSearchResult ──
class PackSearchResult extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('PackSearchResult')
    ..pc<PackInfo>(1, 'packs', PbFieldType.PM, PackInfo.create)
    ..hasRequiredFields = false;

  PackSearchResult() : super();
  PackSearchResult.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  PackSearchResult.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  List<PackInfo> get packs => $_getList(0);

  static PackSearchResult create() => PackSearchResult();
  static PbList<PackSearchResult> createRepeated() => PbList<PackSearchResult>();
  static PackSearchResult getDefault() => _defaultInstance ??= create()..freeze();
  static PackSearchResult? _defaultInstance;
}

// ── DownloadRequest ──
class DownloadRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('DownloadRequest')
    ..aOS(1, 'packUrl', protoName: 'pack_url')
    ..aOS(2, 'packName', protoName: 'pack_name')
    ..hasRequiredFields = false;

  DownloadRequest() : super();
  DownloadRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  DownloadRequest.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  String get packUrl => $_getSZ(0);
  set packUrl(String v) { $_setString(0, v); }
  bool hasPackUrl() => $_has(0);
  void clearPackUrl() => clearField(1);

  String get packName => $_getSZ(1);
  set packName(String v) { $_setString(1, v); }
  bool hasPackName() => $_has(1);
  void clearPackName() => clearField(2);

  static DownloadRequest create() => DownloadRequest();
  static PbList<DownloadRequest> createRepeated() => PbList<DownloadRequest>();
  static DownloadRequest getDefault() => _defaultInstance ??= create()..freeze();
  static DownloadRequest? _defaultInstance;
}

// ── FlashRecord (proto message, not the provider model) ──
class FlashRecordProto extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('FlashRecord')
    ..aOS(1, 'firmwarePath', protoName: 'firmware_path')
    ..aOS(2, 'firmwareHash', protoName: 'firmware_hash')
    ..aOS(3, 'chipName', protoName: 'chip_name')
    ..aOS(4, 'probeName', protoName: 'probe_name')
    ..aInt64(5, 'timestamp')
    ..aOB(6, 'success')
    ..aInt64(7, 'durationMs', protoName: 'duration_ms')
    ..aOS(8, 'errorMessage', protoName: 'error_message')
    ..hasRequiredFields = false;

  FlashRecordProto() : super();
  FlashRecordProto.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  FlashRecordProto.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  String get firmwarePath => $_getSZ(0);
  set firmwarePath(String v) { $_setString(0, v); }
  String get firmwareHash => $_getSZ(1);
  set firmwareHash(String v) { $_setString(1, v); }
  String get chipName => $_getSZ(2);
  set chipName(String v) { $_setString(2, v); }
  String get probeName => $_getSZ(3);
  set probeName(String v) { $_setString(3, v); }
  Int64 get timestamp => $_getI64(4);
  set timestamp(Int64 v) { $_setInt64(4, v); }
  bool get success => $_getBF(5);
  set success(bool v) { $_setBool(5, v); }
  Int64 get durationMs => $_getI64(6);
  set durationMs(Int64 v) { $_setInt64(6, v); }
  String get errorMessage => $_getSZ(7);
  set errorMessage(String v) { $_setString(7, v); }

  static FlashRecordProto create() => FlashRecordProto();
  static PbList<FlashRecordProto> createRepeated() => PbList<FlashRecordProto>();
  static FlashRecordProto getDefault() => _defaultInstance ??= create()..freeze();
  static FlashRecordProto? _defaultInstance;
}

// ── FlashHistoryList ──
class FlashHistoryList extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('FlashHistoryList')
    ..pc<FlashRecordProto>(1, 'records', PbFieldType.PM, FlashRecordProto.create)
    ..hasRequiredFields = false;

  FlashHistoryList() : super();
  FlashHistoryList.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  FlashHistoryList.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);

  @override
  BuilderInfo get info_ => _i;

  List<FlashRecordProto> get records => $_getList(0);

  static FlashHistoryList create() => FlashHistoryList();
  static PbList<FlashHistoryList> createRepeated() => PbList<FlashHistoryList>();
  static FlashHistoryList getDefault() => _defaultInstance ??= create()..freeze();
  static FlashHistoryList? _defaultInstance;
}

// ── ListProbesRequest (Empty message) ──
class ListProbesRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('ListProbesRequest')
    ..hasRequiredFields = false;

  ListProbesRequest() : super();
  ListProbesRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);

  @override
  BuilderInfo get info_ => _i;

  static ListProbesRequest create() => ListProbesRequest();
  static PbList<ListProbesRequest> createRepeated() => PbList<ListProbesRequest>();
  static ListProbesRequest getDefault() => _defaultInstance ??= create()..freeze();
  static ListProbesRequest? _defaultInstance;
}

// ── DisconnectProbeRequest (Empty message) ──
class DisconnectProbeRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('DisconnectProbeRequest')
    ..hasRequiredFields = false;

  DisconnectProbeRequest() : super();
  DisconnectProbeRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);

  @override
  BuilderInfo get info_ => _i;

  static DisconnectProbeRequest create() => DisconnectProbeRequest();
  static PbList<DisconnectProbeRequest> createRepeated() => PbList<DisconnectProbeRequest>();
  static DisconnectProbeRequest getDefault() => _defaultInstance ??= create()..freeze();
  static DisconnectProbeRequest? _defaultInstance;
}

// ── ResetTargetRequest (Empty message) ──
class ResetTargetRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('ResetTargetRequest')
    ..hasRequiredFields = false;

  ResetTargetRequest() : super();
  ResetTargetRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);

  @override
  BuilderInfo get info_ => _i;

  static ResetTargetRequest create() => ResetTargetRequest();
  static PbList<ResetTargetRequest> createRepeated() => PbList<ResetTargetRequest>();
  static ResetTargetRequest getDefault() => _defaultInstance ??= create()..freeze();
  static ResetTargetRequest? _defaultInstance;
}

// ── ReadChipIdRequest (Empty message) ──
class ReadChipIdRequest extends GeneratedMessage {
  static final BuilderInfo _i = BuilderInfo('ReadChipIdRequest')
    ..hasRequiredFields = false;

  ReadChipIdRequest() : super();
  ReadChipIdRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);

  @override
  BuilderInfo get info_ => _i;

  static ReadChipIdRequest create() => ReadChipIdRequest();
  static PbList<ReadChipIdRequest> createRepeated() => PbList<ReadChipIdRequest>();
  static ReadChipIdRequest getDefault() => _defaultInstance ??= create()..freeze();
  static ReadChipIdRequest? _defaultInstance;
}
