// Generated gRPC stubs for dap_flash.proto
// In production, this file is generated by protoc --dart_out=grpc:lib/proto
import 'package:grpc/grpc.dart';
import 'dap_flash.pb.dart';

// ── Service Client ──
class DapFlashServiceClient extends Client {
  static final _$listProbes = ClientMethod<ListProbesRequest, ProbeList>(
    '/dap_flash.DapFlashService/ListProbes',
    (ListProbesRequest value) => value.writeToBuffer(),
    (List<int> value) => ProbeList.fromBuffer(value),
  );

  static final _$connectProbe = ClientMethod<ConnectRequest, ConnectResponse>(
    '/dap_flash.DapFlashService/ConnectProbe',
    (ConnectRequest value) => value.writeToBuffer(),
    (List<int> value) => ConnectResponse.fromBuffer(value),
  );

  static final _$disconnectProbe = ClientMethod<DisconnectProbeRequest, DisconnectProbeRequest>(
    '/dap_flash.DapFlashService/DisconnectProbe',
    (DisconnectProbeRequest value) => value.writeToBuffer(),
    (List<int> value) => DisconnectProbeRequest.fromBuffer(value),
  );

  static final _$flashFirmware = ClientMethod<FlashRequest, ProgressUpdate>(
    '/dap_flash.DapFlashService/FlashFirmware',
    (FlashRequest value) => value.writeToBuffer(),
    (List<int> value) => ProgressUpdate.fromBuffer(value),
  );

  static final _$eraseChip = ClientMethod<EraseRequest, ProgressUpdate>(
    '/dap_flash.DapFlashService/EraseChip',
    (EraseRequest value) => value.writeToBuffer(),
    (List<int> value) => ProgressUpdate.fromBuffer(value),
  );

  static final _$resetTarget = ClientMethod<ResetTargetRequest, OperationResult>(
    '/dap_flash.DapFlashService/ResetTarget',
    (ResetTargetRequest value) => value.writeToBuffer(),
    (List<int> value) => OperationResult.fromBuffer(value),
  );

  static final _$readChipId = ClientMethod<ReadChipIdRequest, ChipIdResult>(
    '/dap_flash.DapFlashService/ReadChipId',
    (ReadChipIdRequest value) => value.writeToBuffer(),
    (List<int> value) => ChipIdResult.fromBuffer(value),
  );

  static final _$listPacks = ClientMethod<ListProbesRequest, PackList>(
    '/dap_flash.DapFlashService/ListPacks',
    (ListProbesRequest value) => value.writeToBuffer(),
    (List<int> value) => PackList.fromBuffer(value),
  );

  static final _$searchPacks = ClientMethod<SearchRequest, PackSearchResult>(
    '/dap_flash.DapFlashService/SearchPacks',
    (SearchRequest value) => value.writeToBuffer(),
    (List<int> value) => PackSearchResult.fromBuffer(value),
  );

  static final _$downloadPack = ClientMethod<DownloadRequest, ProgressUpdate>(
    '/dap_flash.DapFlashService/DownloadPack',
    (DownloadRequest value) => value.writeToBuffer(),
    (List<int> value) => ProgressUpdate.fromBuffer(value),
  );

  static final _$getFlashHistory = ClientMethod<ListProbesRequest, FlashHistoryList>(
    '/dap_flash.DapFlashService/GetFlashHistory',
    (ListProbesRequest value) => value.writeToBuffer(),
    (List<int> value) => FlashHistoryList.fromBuffer(value),
  );

  DapFlashServiceClient(ClientChannel channel, {CallOptions? options})
      : super(channel, options: options);

  ResponseFuture<ProbeList> listProbes(ListProbesRequest request, {CallOptions? options}) {
    return $createUnaryCall(_$listProbes, request, options: options);
  }

  ResponseFuture<ConnectResponse> connectProbe(ConnectRequest request, {CallOptions? options}) {
    return $createUnaryCall(_$connectProbe, request, options: options);
  }

  ResponseFuture<DisconnectProbeRequest> disconnectProbe(DisconnectProbeRequest request, {CallOptions? options}) {
    return $createUnaryCall(_$disconnectProbe, request, options: options);
  }

  ResponseStream<ProgressUpdate> flashFirmware(FlashRequest request, {CallOptions? options}) {
    return $createStreamingCall(_$flashFirmware, Stream.fromIterable([request]), options: options);
  }

  ResponseStream<ProgressUpdate> eraseChip(EraseRequest request, {CallOptions? options}) {
    return $createStreamingCall(_$eraseChip, Stream.fromIterable([request]), options: options);
  }

  ResponseFuture<OperationResult> resetTarget(ResetTargetRequest request, {CallOptions? options}) {
    return $createUnaryCall(_$resetTarget, request, options: options);
  }

  ResponseFuture<ChipIdResult> readChipId(ReadChipIdRequest request, {CallOptions? options}) {
    return $createUnaryCall(_$readChipId, request, options: options);
  }

  ResponseFuture<PackList> listPacks(ListProbesRequest request, {CallOptions? options}) {
    return $createUnaryCall(_$listPacks, request, options: options);
  }

  ResponseFuture<PackSearchResult> searchPacks(SearchRequest request, {CallOptions? options}) {
    return $createUnaryCall(_$searchPacks, request, options: options);
  }

  ResponseStream<ProgressUpdate> downloadPack(DownloadRequest request, {CallOptions? options}) {
    return $createStreamingCall(_$downloadPack, Stream.fromIterable([request]), options: options);
  }

  ResponseFuture<FlashHistoryList> getFlashHistory(ListProbesRequest request, {CallOptions? options}) {
    return $createUnaryCall(_$getFlashHistory, request, options: options);
  }
}
